### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by takahashi0212** [takahashi0212/furima_28827#10]
# URL
https://furima-28827.herokuapp.com/
# Basic認証のIDとパスワード
ID: admin  ps: 2222
# 出品者用のメールアドレスとパスワード
test@aaa.com         ps: aaaa1111
# 購入者用のメールアドレスとパスワード
aaa@aaa.com          ps: aaaa1111
# 購入用カードの番号・期限・セキュリティコード
4242424242424242
2/ 23
123

**Comment by oooooooba** [comment]
takahashi0212さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・必須項目を入力し、ユーザー登録ができる
メールアドレス欄に「tec@tec」と入力して登録を試みましたが、「Email is invalid
」と表示され、新規登録が行えませんでした。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takahashi0212** [comment]
ご確認ありがとうございます。
「メールアドレス欄に「tec@tec」と入力して登録を試みましたが、「Email is invalid
」と表示され、新規登録が行えませんでした。」とご指摘を頂いたのですが、「.com」を入れて頂いたら登録できると思います。
再度確認して頂けませんでしょうか？

**Comment by oooooooba** [comment]
takahashi0212さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・商品詳細機能の確認
商品詳細ページに、商品説明欄がございませんので修正をお願いします

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takahashi0212** [comment]
ご確認ありがとうございます。
商品詳細ページに、商品説明欄のご指摘の修正をしました。
確認お願いします。

**Comment by oooooooba** [comment]
takahashi0212 さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、完成要件は全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしていただきたく存じます。
・商品削除機能の確認
購入済みの商品を削除しようとするとエラーになる

※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。
